version: '3'
services:
  database:
    image: mongo:4.2
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=root-db
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
